### ISSUE TITLE
where train.py? and code use dg-pnp?

### ISSUE THREAD

**Issue by xumingkun9806** [maplect/DGECN_CVPR2022#1]
thanks for your work,but I don't find the train.py and in the inference the code use cv2.solvePnPRansac not your dg_pnp?

**Comment by maplect** [comment]
Thanks for your interest in our work. This is a cooperation project with Huawei Ascend, we will realease our full code [here](https://gitee.com/ascend/ModelZoo-PyTorch/tree/master/PyTorch/contrib/cv), and this may take some time.

**Comment by xumingkun9806** [comment]
ok，thanks！
